### ISSUE TITLE
Add Python wrapper

### ISSUE THREAD

**Issue by GlenRice-NOAA** [OpenNavigationSurface/BAG#4]
Adding a Python wrapper to the BAG library would enable further use of the BAG reference library and format.

**Comment by GlenRice-NOAA** [comment]
Adding continuous integration to the BAG repository would enable building for specific needs and environments, and make the reference library more functional.

**Comment by GlenRice-NOAA** [comment]
This should be integrated into work associated with #7.

**Comment by GlenRice-NOAA** [comment]
I propose we create python bindings using [Swig ](http://www.swig.org/) to allow for other language extensions.

**Comment by johnsonst** [comment]
> I propose we create python bindings using [Swig ](http://www.swig.org/) to allow for other language extensions.

The addition or requirement of third party libraries and packages cause issues on DoD networks.   If it can be added and not be required then I have no objection, but if this adds a requirement to use the python wrapper then it will likely cause significant issues here.  This is especially true of development tools that cannot be downloaded directly from the OS distributer.

**Comment by giumas** [comment]
>  If it can be added and not be required then I have no objection, but if this adds a requirement to use the python wrapper then it will likely cause significant issues here.

I suspect that Swig is already in use on DoD networks (e.g., [GDAL uses SWIG](https://trac.osgeo.org/gdal/wiki/SWIG)). 

However, I agree that the Python binding should be optional (using CMake). When the option is off, then the SWIG dependency goes away. As such, SWIG should NOT be added/distributed with the BAG library. code.
