### ISSUE TITLE
Build issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by rolker** [OpenNavigationSurface/BAG#60]
Attempting to configure the V2 branch of the project using CMake on Ubuntu 20.04 with dependencies installed via apt results in the following error:

HDF5::HDF5 not found.

The problems seems to be that in CMake's supplied FindHDF5.cmake module, the HDF5::HDF5 target was added in a later version of CMake than the one included with Ubuntu 20.04.

Unless someone has another idea, I'll try to add checks and workarounds in CMakelist to overcome this problem.

This does raise the question of which range of platforms and versions do we want V2 to support?

The ROS based framework I currently work on for uncrewed marine systems is based on Ubuntu 20.04 and ROS Noetic. Conda is not used and apt based dependencies are much prefered.  I'll work under the assumtion that this is within the range we want to support for now.

**Comment by selimnairb** [comment]
@rolker Okay to close this issue?

**Comment by rolker** [comment]
Yes, builds fine on Ubuntu 20.04 now.
