### ISSUE TITLE
CI: Refactor Windows tests from Appveyor to GitHub Actions workflow

### ISSUE THREAD

**Issue by selimnairb** [OpenNavigationSurface/BAG#73]
Appveyor builds are broken due to a strange Conda error (unable to find tqdm, see [here](https://ci.appveyor.com/project/giumas/bag/builds/47931647)). Given this, and since the GitHub Actions workflows seem to work well, it's probably time to consolidate the Windows build to GH Actions. In the process, we should also move away from using Conda for Windows builds and instead build dependencies by hand.

**Comment by giumas** [comment]
> we should also move away from using Conda for Windows builds and instead build dependencies by hand.

I agree in principle, but it may create integration issues downstream. For instance, HDF building parameters may conflict with other linked library (e.g., GDAL).
