### ISSUE TITLE
Update the BAG format to comply with CF conventions

### ISSUE THREAD

**Issue by GlenRice-NOAA** [OpenNavigationSurface/BAG#9]
Updating the BAG format to comply with [CF conventions](http://cfconventions.org/) was suggested at the Open Navigation Surface Working Group Meeting at US Hydro 2019.  The outcome of this discussion was that more research was needed to understand the value and repercussions of this change.  This is a handle for further discussion.

**Comment by GlenRice-NOAA** [comment]
Does adding these conventions (or just the metadata associated with georeferencing) necessarily break backward compatibility with the 1.x API?

**Comment by johnsonst** [comment]
1) Are you modifying or removing any existing items?
2) Are you removing or adding mandatory items?


If you 1) modify or remove items or 2) change what is mandatory then you likely affect backwards compatibility in both directions (1.X reading 2.0 and 2.0 reading 1.X).

**Comment by GlenRice-NOAA** [comment]
Understood.  I'm just not clear that the CF conventions do this to the current structure.  I was just asking the question to avoid assumptions.

> 1. Are you modifying or removing any existing items?
> 2. Are you removing or adding mandatory items?
> 
> If you 1) modify or remove items or 2) change what is mandatory then you likely affect backwards compatibility in both directions (1.X reading 2.0 and 2.0 reading 1.X).

**Comment by johnsonst** [comment]
It will depend on the actual implementation.  If the current structure is only modified with additional metadata/structures that are optional, then you might not break compatibility.  I think there is probably a means to do it without breaking compatibility.

**Comment by GlenRice-NOAA** [comment]
Noting this was discussed in [2019-03-20 meeting minutes](http://www.opennavsurf.org/meetings/onswg_mtg_2019-03-20.pdf) in 2.6

**Comment by GlenRice-NOAA** [comment]
In the near term I believe we decided not do take this on.
